package auth;

public enum Permission {
    VIEW_TOUR_INFO,
    VIEW_FAIR_INFO,
    VIEW_TOUR_REVIEW,
    RU_FROM_TOUR,
    AR_TOUR_ASSIGNMENT,
    REPORT_TOUR_TIMES,
    AR_TOUR_REQUESTS,

    REQUEST_TOUR_CHANGES,
    AR_TOUR_CHANGES,
    ASSIGN_OTHER_GUIDE,
    MANAGE_GUIDE_EXPERIENCE,

    AR_GUIDE_APPLICATIONS,
    INVITE_GUIDE_TO_FAIR,
    FIRE_GUIDE_OR_ADVISOR,
    AR_FAIR_INVITATIONS,
    VIEW_WORK_DONE_BY_GUIDE,

    TOTAL_ANALYTICS_ACCESS,
}
