package mailService;

public enum MailType {
    TOUR_APPLICATION_CONFIRMATION,
    TOUR_APPLICATION_ACCEPTANCE,
    TOUR_APPLICATION_REJECTION,
    TOUR_CHANGE,
    TOUR_CANCEL,
    TOUR_CANCEL_CONFIRMATION,
    TOUR_CHANGE_CONFIRMATION,
    TOUR_CHANGE_REJECTION,

    FAIR_APPLICATION_CONFIRMATION,
    FAIR_APPLICATION_ACCEPTANCE,
    FAIR_APPLICATION_REJECTION,


    GUIDE_APPLICATION_CONFIRMATION,
    GUIDE_ACCEPTANCE,
    GUIDE_REJECTION,
    GUIDE_FAIR_INVITATION,

    GUIDE_WITHDRAW_FROM_TOUR,
    GUIDE_TOUR_ENROLL_NOTIFICATION,

    GUIDE_TOUR_ASSIGNMENT,
    GUIDE_TOUR_ASSIGNMENT_ACCEPTION,
}
